# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:4.4
    #restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: P@ssw0rd123
      #SSL: True
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    command: --serviceExecutor adaptive
    
